site_name: DANS Preferred Formats
site_description: >- 
  File Formats and Digital Preservation:
  catalogue of data types with associated file formats,
  supplied with recommendations
  on their suitability
  to be preserved for the long term.

site_url: 'https://Dans-labs.github.io/formats/'

site_author: Dirk Roorda based on input of colleagues Valentijn Gilissen and Henk van den Berg

extra:
  adobe: https://www.adobe.com
  angular: https://angular.io
  author: mailto:dirk.roorda@dans.knaw.nl
  babel: https://babeljs.io
  bullzip: http://www.bullzip.com/products/pdf/info.php
  cbook: https://www.academia.edu/37784778/The_C_Programming_Language_by_Brian_W.Kernighan_Dennis_M.Ritchie_2nd_Ed_
  cgi: https://en.wikipedia.org/wiki/Common_Gateway_Interface
  chromev8: https://v8.dev
  coptr: http://coptr.digipres.org
  cpp: https://isocpp.org
  css: https://www.w3.org/TR/css-2018/
  cssmdn: https://developer.mozilla.org/en-US/docs/Web/CSS
  csvrfc: https://tools.ietf.org/html/rfc4180
  dans: https://www.dans.knaw.nl
  dbase: https://www.dbase.com/Knowledgebase/dbulletin/bu03_b.htm
  docs: https://Dans-labs.github.io/formats/
  easy: https://easy.dans.knaw.nl
  es6: https://en.wikipedia.org/wiki/ECMAScript#6th_Edition_-_ECMAScript_2015
  es6features: http://es6-features.org/#Constants
  fileinfo: https://fileinfo.com/extension
  formats: https://github.com/Dans-labs/formats
  ghpages: https://pages.github.com
  gif: https://www.w3.org/Graphics/GIF/spec-gif87.txt
  gzip: https://www.gzip.org
  hdf5: https://www.hdfgroup.org/solutions/hdf5/
  hdf5tools: https://support.hdfgroup.org/products/hdf5_tools/
  html: https://www.w3.org/TR/html/
  html52: https://www.w3.org/TR/html52/introduction.html#introduction-history
  htmlliving: https://html.spec.whatwg.org
  htmlmdn: https://developer.mozilla.org/en-US/docs/Web/HTML
  imagemagick: https://imagemagick.org/index.php
  irfanview: https://www.irfanview.com
  issues: https://github.com/Dans-labs/formats/issues
  java: https://www.oracle.com/java/
  jpeg: https://www.w3.org/Graphics/JPEG/itu-t81.pdf
  jupyter: https://jupyter.org
  js: http://ecma-international.org/ecma-262/9.0/index.html#Title
  jsmdn: https://developer.mozilla.org/en-US/docs/Web/JavaScript
  json: https://json.org
  jsx: https://reactjs.org
  latex: https://www.latex-project.org
  libreoffice: https://www.libreoffice.org
  markdown: https://daringfireball.net/projects/markdown/syntax
  markupw3c: https://www.w3.org/MarkUp/
  mathml: https://www.w3.org/Math/
  mdn: https://developer.mozilla.org/en-US/
  mkdocs: https://www.mkdocs.org
  mongodb: https://www.mongodb.com
  msaccess: https://products.office.com/en/access
  msaccesscom: https://techcommunity.microsoft.com/t5/Access/ct-p/Access_Cat
  msexcel: https://products.office.com/en/excel
  msword: https://products.office.com/en/word
  mysql: https://www.mysql.com
  nodejs: https://nodejs.org/en/
  ooxml: https://www.ecma-international.org/publications/standards/Ecma-376.htm
  pascal: http://scihi.org/nikolaus-wirth-pascal/
  pdf: https://www.pdfa.org/resource/iso-32000-1-pdf-1-7/
  pdfa: https://www.pdfa.org/resource/iso-19005-pdfa/
  perl: http://www.perl.org
  png: http://www.libpng.org/pub/png/
  postscript: https://www.adobe.com/products/postscript.html
  preferredFormats: https://dans.knaw.nl/en/deposit/information-about-depositing-data/before-depositing/file-formats?set_language=en
  prolog: https://www.swi-prolog.org
  python: https://www.python.org
  react: https://reactjs.org
  readthedocs: https://readthedocs.org
  relaxng: https://relaxng.org
  ruby: https://www.ruby-lang.org/en/
  rubyrails: https://rubyonrails.org
  scala: https://www.scala-lang.org
  sgml: https://www.w3.org/MarkUp/SGML/
  siard: https://www.bar.admin.ch/bar/en/home/archiving/tools/siard-suite.html
  smil: https://www.w3.org/AudioVideo/
  sqldoc: https://dev.mysql.com/doc/refman/8.0/en/sql-syntax.html
  svgmdn: https://developer.mozilla.org/en-US/docs/Web/SVG
  tar: https://www.gnu.org/software/tar/
  tei: https://tei-c.org
  tex: https://ctan.org
  tiff: https://tools.ietf.org/html/rfc2306
  unicode: http://unicode.org
  vue: https://vuejs.org
  w3c: https://www.w3.org
  w3cwhatwg: https://www.w3.org/2019/04/WHATWG-W3C-MOU.html
  webpack: https://webpack.js.org
  whatwg: https://whatwg.org
  wikipedia: https://en.wikipedia.org/wiki
  woff: https://www.w3.org/TR/WOFF/
  woff2: https://www.w3.org/TR/WOFF2/
  xhtml: https://www.w3.org/TR/xhtml11/
  xml: https://www.w3.org/TR/xml/
  xmldtd: https://www.w3.org/TR/REC-xml/#dt-doctype
  xmlschema: https://www.w3.org/standards/xml/schema
  xslt: https://www.w3.org/TR/xslt/all/
  yaml: https://yaml.org

theme:
  name: material
  logo: 'images/formats.png'
  favicon: 'images/formats.png'
  feature:
    tabs: false
  palette:
    primary: red
    accent: cyan

repo_url: 'https://github.com/Dans-labs/formats/'

strict: false

nav:
  - Home: 'index.md'
  - Data Types:
    - Data (container): 'dataTypes/dataContainer.md'
    - Database: 'dataTypes/database.md'
    - Font: 'dataTypes/font.md'
    - Image: 'dataTypes/image.md'
    - Markup: 'dataTypes/markup.md'
    - Program code: 'dataTypes/programCode.md'
    - Spreadsheet: 'dataTypes/spreadsheet.md'
    - Text (formatted): 'dataTypes/textFormatted.md'
    - Text (plain): 'dataTypes/textPlain.md'
  - File Formats (by data type):
    - Data (container):
      - JSON: 'fileFormats/json.md'
      - SQL: 'fileFormats/sql.md'
      - TAR: 'fileFormats/tar.md'
      - XML: 'fileFormats/xml.md'
      - YAML: 'fileFormats/yaml.md'
    - Database:
      - Access: 'fileFormats/access.md'
      - CSV: 'fileFormats/csv.md'
      - HDF5: 'fileFormats/hdf5.md'
      - SIARD: 'fileFormats/siard.md'
      - SQL: 'fileFormats/sql.md'
      - XML: 'fileFormats/xml.md'
      - dbase: 'fileFormats/dbase.md'
    - Font:
      - WOFF: 'fileFormats/woff.md'
      - WOFF2: 'fileFormats/woff2.md'
    - Image:
      - GIF: 'fileFormats/gif.md'
      - JPEG: 'fileFormats/jpeg.md'
      - PDF: 'fileFormats/pdf.md'
      - PDF/A: 'fileFormats/pdfa.md'
      - PNG: 'fileFormats/png.md'
      - PostScript: 'fileFormats/postscript.md'
      - SVG: 'fileFormats/svg.md'
      - TIFF: 'fileFormats/tiff.md'
    - Markup:
      - CSS: 'fileFormats/css.md'
      - HTML: 'fileFormats/html.md'
      - JSX: 'fileFormats/jsx.md'
      - JavaScript: 'fileFormats/javascript.md'
      - Markdown: 'fileFormats/markdown.md'
      - SGML: 'fileFormats/sgml.md'
      - TeX: 'fileFormats/tex.md'
      - XHTML: 'fileFormats/xhtml.md'
      - XML: 'fileFormats/xml.md'
      - XSLT: 'fileFormats/xslt.md'
    - Program code:
      - C: 'fileFormats/c.md'
      - CPP: 'fileFormats/cpp.md'
      - JAVA: 'fileFormats/java.md'
      - JSX: 'fileFormats/jsx.md'
      - JavaScript: 'fileFormats/javascript.md'
      - Pascal: 'fileFormats/pascal.md'
      - Perl: 'fileFormats/perl.md'
      - Prolog: 'fileFormats/prolog.md'
      - Python: 'fileFormats/python.md'
      - Ruby: 'fileFormats/ruby.md'
      - Scala: 'fileFormats/scala.md'
      - XSLT: 'fileFormats/xslt.md'
    - Spreadsheet:
      - ODS: 'fileFormats/ods.md'
      - XLS: 'fileFormats/xls.md'
      - XLSX: 'fileFormats/xlsx.md'
    - Text (formatted):
      - DOC: 'fileFormats/doc.md'
      - DOCX: 'fileFormats/docx.md'
      - ODT: 'fileFormats/odt.md'
      - PDF/A: 'fileFormats/pdfa.md'
    - Text (plain):
      - CSS: 'fileFormats/css.md'
      - CSV: 'fileFormats/csv.md'
      - HTML: 'fileFormats/html.md'
      - JSON: 'fileFormats/json.md'
      - Markdown: 'fileFormats/markdown.md'
      - SQL: 'fileFormats/sql.md'
      - TeX: 'fileFormats/tex.md'
      - Text: 'fileFormats/text.md'
      - XML: 'fileFormats/xml.md'
      - YAML: 'fileFormats/yaml.md'
  - File Formats (A-Z):
    - Access: 'fileFormats/access.md'
    - C: 'fileFormats/c.md'
    - CPP: 'fileFormats/cpp.md'
    - CSS: 'fileFormats/css.md'
    - CSV: 'fileFormats/csv.md'
    - DOC: 'fileFormats/doc.md'
    - DOCX: 'fileFormats/docx.md'
    - GIF: 'fileFormats/gif.md'
    - HDF5: 'fileFormats/hdf5.md'
    - HTML: 'fileFormats/html.md'
    - JAVA: 'fileFormats/java.md'
    - JPEG: 'fileFormats/jpeg.md'
    - JSON: 'fileFormats/json.md'
    - JSX: 'fileFormats/jsx.md'
    - JavaScript: 'fileFormats/javascript.md'
    - Markdown: 'fileFormats/markdown.md'
    - ODS: 'fileFormats/ods.md'
    - ODT: 'fileFormats/odt.md'
    - PDF: 'fileFormats/pdf.md'
    - PDF/A: 'fileFormats/pdfa.md'
    - PNG: 'fileFormats/png.md'
    - Pascal: 'fileFormats/pascal.md'
    - Perl: 'fileFormats/perl.md'
    - PostScript: 'fileFormats/postscript.md'
    - Prolog: 'fileFormats/prolog.md'
    - Python: 'fileFormats/python.md'
    - Ruby: 'fileFormats/ruby.md'
    - SGML: 'fileFormats/sgml.md'
    - SIARD: 'fileFormats/siard.md'
    - SQL: 'fileFormats/sql.md'
    - SVG: 'fileFormats/svg.md'
    - Scala: 'fileFormats/scala.md'
    - TAR: 'fileFormats/tar.md'
    - TIFF: 'fileFormats/tiff.md'
    - TeX: 'fileFormats/tex.md'
    - Text: 'fileFormats/text.md'
    - WOFF: 'fileFormats/woff.md'
    - WOFF2: 'fileFormats/woff2.md'
    - XHTML: 'fileFormats/xhtml.md'
    - XLS: 'fileFormats/xls.md'
    - XLSX: 'fileFormats/xlsx.md'
    - XML: 'fileFormats/xml.md'
    - XSLT: 'fileFormats/xslt.md'
    - YAML: 'fileFormats/yaml.md'
    - dbase: 'fileFormats/dbase.md'
  - Extensions:
    - .accdb: 'extensions/accdb.md'
    - .c: 'extensions/c.md'
    - .cfg: 'extensions/cfg.md'
    - .cpp: 'extensions/cpp.md'
    - .css: 'extensions/css.md'
    - .csv: 'extensions/csv.md'
    - .dbf: 'extensions/dbf.md'
    - .doc: 'extensions/doc.md'
    - .docx: 'extensions/docx.md'
    - .eps: 'extensions/eps.md'
    - .es: 'extensions/es.md'
    - .gif: 'extensions/gif.md'
    - .h: 'extensions/h.md'
    - .hdf5: 'extensions/hdf5.md'
    - .htm: 'extensions/htm.md'
    - .html: 'extensions/html.md'
    - .ini: 'extensions/ini.md'
    - .java: 'extensions/java.md'
    - .jpeg: 'extensions/jpeg.md'
    - .jpg: 'extensions/jpg.md'
    - .js: 'extensions/js.md'
    - .json: 'extensions/json.md'
    - .jsx: 'extensions/jsx.md'
    - .log: 'extensions/log.md'
    - .lst: 'extensions/lst.md'
    - .md: 'extensions/md.md'
    - .mdb: 'extensions/mdb.md'
    - .ods: 'extensions/ods.md'
    - .odt: 'extensions/odt.md'
    - .p: 'extensions/p.md'
    - .pas: 'extensions/pas.md'
    - .pdf: 'extensions/pdf.md'
    - .pl: 'extensions/pl.md'
    - .png: 'extensions/png.md'
    - .ps: 'extensions/ps.md'
    - .py: 'extensions/py.md'
    - .rb: 'extensions/rb.md'
    - .scala: 'extensions/scala.md'
    - .siard: 'extensions/siard.md'
    - .sql: 'extensions/sql.md'
    - .sty: 'extensions/sty.md'
    - .svg: 'extensions/svg.md'
    - .tar: 'extensions/tar.md'
    - .tex: 'extensions/tex.md'
    - .text: 'extensions/text.md'
    - .tif: 'extensions/tif.md'
    - .tiff: 'extensions/tiff.md'
    - .tsv: 'extensions/tsv.md'
    - .txt: 'extensions/txt.md'
    - .woff: 'extensions/woff.md'
    - .woff2: 'extensions/woff2.md'
    - .xls: 'extensions/xls.md'
    - .xlsx: 'extensions/xlsx.md'
    - .xml: 'extensions/xml.md'
    - .xsl: 'extensions/xsl.md'
    - .xslt: 'extensions/xslt.md'
    - .yaml: 'extensions/yaml.md'
  - Build: 'help.md'

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

plugins:
  - markdownextradata
